"""create job sync run tables

Revision ID: 0dbe1758f41c
Revises: a3e8f3836dc7
Create Date: 2026-08-09 06:23:57.812937

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dbe1758f41c"
down_revision: str | Sequence[str] | None = "a3e8f3836dc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_sync_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'partial', 'failed')",
            name="ck_job_sync_runs_status",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_sync_runs")),
    )
    op.create_index(
        "ix_job_sync_runs_started_at",
        "job_sync_runs",
        ["started_at"],
        unique=False,
    )
    op.create_table(
        "job_sync_run_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fetched_records", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duplicates", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("conflicts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rejected", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("skipped_non_remote", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name="ck_job_sync_run_sources_status",
        ),
        sa.CheckConstraint(
            """
            pages_fetched >= 0
            AND fetched_records >= 0
            AND created >= 0
            AND updated >= 0
            AND duplicates >= 0
            AND conflicts >= 0
            AND rejected >= 0
            AND skipped_non_remote >= 0
            """,
            name="ck_job_sync_run_sources_counts_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["job_sync_runs.id"],
            name=op.f("fk_job_sync_run_sources_run_id_job_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_sync_run_sources")),
        sa.UniqueConstraint("run_id", "source_name", name="uq_job_sync_run_sources_run_source"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_sync_run_sources")
    op.drop_index("ix_job_sync_runs_started_at", table_name="job_sync_runs")
    op.drop_table("job_sync_runs")
    # ### end Alembic commands ###
