"""create jobs table

Revision ID: 1dcaae56c7fc
Revises: 3f6e77a27881
Create Date: 2026-08-03 13:51:42.782907

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dcaae56c7fc"
down_revision: str | Sequence[str] | None = "3f6e77a27881"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("source_job_id", sa.String(length=255), nullable=False),
        sa.Column("deduplication_key", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("application_url", sa.String(length=2048), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "remote_regions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("employment_type", sa.String(length=50), nullable=True),
        sa.Column("experience_level", sa.String(length=50), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_remote", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (salary_min IS NULL AND salary_max IS NULL)\n            OR salary_currency IS NOT NULL\n            ",
            name="ck_jobs_salary_currency",
        ),
        sa.CheckConstraint(
            "\n            salary_min IS NULL\n            OR salary_max IS NULL\n            OR salary_min <= salary_max\n            ",
            name="ck_jobs_salary_range",
        ),
        sa.CheckConstraint(
            "salary_max IS NULL OR salary_max >= 0", name="ck_jobs_salary_max_non_negative"
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_min >= 0", name="ck_jobs_salary_min_non_negative"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("deduplication_key", name="uq_jobs_deduplication_key"),
        sa.UniqueConstraint("source_name", "source_job_id", name="uq_jobs_source_job"),
    )
    op.create_index(
        "ix_jobs_active_published_at", "jobs", ["is_active", "published_at"], unique=False
    )
    op.create_index("ix_jobs_skills_gin", "jobs", ["skills"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_skills_gin", table_name="jobs", postgresql_using="gin")
    op.drop_index("ix_jobs_active_published_at", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
