"""add extracted skills to cv documents

Revision ID: 3f6e77a27881
Revises: 45e6e1d5bc42
Create Date: 2026-08-03 09:48:01.154998

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f6e77a27881"
down_revision: str | Sequence[str] | None = "45e6e1d5bc42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cv_documents",
        sa.Column(
            "extracted_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "cv_documents", sa.Column("skills_extraction_version", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cv_documents", "skills_extraction_version")
    op.drop_column("cv_documents", "extracted_skills")
    # ### end Alembic commands ###
